import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

test('account approval, authorization, session revocation and private server files', { skip: !process.env.TEST_DATABASE_URL }, async t => {
  const cwd = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
  const server = spawn(process.execPath, ['server/server.mjs'], { cwd, env: { ...process.env, PORT: '0', DATABASE_URL: process.env.TEST_DATABASE_URL }, windowsHide: true });
  t.after(() => server.kill());
  const base = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Server did not start')), 10000);
    server.stdout.on('data', chunk => { const match = String(chunk).match(/http:\/\/127\.0\.0\.1:\d+/); if (match) { clearTimeout(timeout); resolve(match[0]); } });
    server.on('error', reject);
  });
  const request = (url, body, cookie = '', extra = {}) => fetch(base + url, { method: body === undefined ? 'GET' : 'POST', headers: { 'Content-Type': 'application/json', Cookie: cookie, ...extra }, body: body === undefined ? undefined : JSON.stringify(body) });
  const duplicate = spawn(process.execPath, ['server/server.mjs'], { cwd, env: { ...process.env, PORT: new URL(base).port, DATABASE_URL: process.env.TEST_DATABASE_URL }, windowsHide: true });
  t.after(() => duplicate.kill());
  let startupError = '';
  duplicate.stderr.on('data', chunk => { startupError += chunk; });
  const duplicateExit = await new Promise((resolve, reject) => { duplicate.on('close', resolve); duplicate.on('error', reject); });
  assert.equal(duplicateExit, 1);
  assert.match(startupError, /already in use/);
  assert.match(startupError, /Ctrl\+C/);
  assert.doesNotMatch(startupError, /Unhandled 'error' event/);
  assert.equal((await (await request('/api/status')).json()).setupRequired, true);
  const adminResponse = await request('/api/register', { name: 'Admin', email: 'admin@example.test', password: 'secure-example-123' });
  assert.equal(adminResponse.status, 200);
  const adminCookie = adminResponse.headers.get('set-cookie').split(';')[0];
  assert.ok(adminResponse.headers.get('set-cookie').includes('HttpOnly'));
  assert.equal((await adminResponse.json()).user.role, 'admin');
  const project = { id: '11111111-1111-4111-8111-111111111111', name: 'Synced test', filename: 'test.wav', size: 3, duration: 1, transcript: '', settings: [], createdAt: Date.now(), updatedAt: Date.now(), chunks: 1, resetChunks: true };
  assert.equal((await request('/api/projects', project, adminCookie)).status, 200);
  assert.equal((await request('/api/projects/chunk', { id: project.id, index: 0, data: 'AQID' }, adminCookie)).status, 200);
  const projectList = await (await request('/api/projects', undefined, adminCookie)).json();
  assert.equal(projectList.projects.length, 1); assert.equal(projectList.projects[0].name, 'Synced test');
  assert.equal((await (await request(`/api/projects/${project.id}/chunks/0`, undefined, adminCookie)).json()).data, 'AQID');
  assert.equal((await request('/api/projects/delete', { id: project.id }, adminCookie)).status, 200);
  const deletedList = await (await request('/api/projects', undefined, adminCookie)).json();
  assert.equal(deletedList.projects.length, 0); assert.equal(deletedList.deleted[0].id, project.id);
  const registered = await request('/api/register', { name: 'Artist', email: 'artist@example.test', password: 'secure-example-456' });
  assert.equal(registered.status, 201); assert.equal((await registered.json()).pending, true);
  assert.equal((await request('/api/login', { email: 'artist@example.test', password: 'secure-example-456' })).status, 403);
  assert.equal((await request('/api/admin/users')).status, 401);
  const { users } = await (await request('/api/admin/users', undefined, adminCookie)).json();
  assert.equal(users.length, 2); assert.ok(users.every(user => !('password' in user)));
  const artist = users.find(user => user.role === 'user');
  assert.equal((await request('/api/admin/users', { id: artist.id, status: 'active' }, adminCookie)).status, 200);
  const login = await request('/api/login', { email: 'artist@example.test', password: 'secure-example-456' });
  assert.equal(login.status, 200); const artistCookie = login.headers.get('set-cookie').split(';')[0];
  assert.equal((await request('/api/admin/users', undefined, artistCookie)).status, 403);
  assert.equal((await request('/api/admin/users', { id: artist.id, status: 'suspended' }, adminCookie)).status, 200);
  assert.equal((await (await request('/api/status', undefined, artistCookie)).json()).user, null);
  assert.equal((await request('/api/logout', {}, adminCookie, { Origin: 'https://example.invalid' })).status, 403);
  for (const file of ['/server/server.mjs', '/data/studio.db', '/package.json']) assert.equal((await request(file)).status, 404);
  assert.equal((await request('/')).status, 200);
  assert.equal((await request('/api/logout', {}, adminCookie)).status, 200);
  assert.equal((await request('/api/admin/users', undefined, adminCookie)).status, 401);
});
