import { test, expect } from '@playwright/test';
import { encodeWav } from '../public/audio.js';
import { readFile } from 'node:fs/promises';

test('desktop and mobile studio, real audio upload, account approval, saved edits, WAV export', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'A good day to create.' })).toBeVisible();
  await expect(page.locator('.waveform-area canvas')).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect(page.locator('#elapsed')).not.toHaveText('0:00', { timeout: 5000 });
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('tab', { name: /^Stems/ }).click();
  await expect(page.locator('.track-row')).toHaveCount(4);
  await page.getByRole('button', { name: 'Mute Melody', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mute Melody', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.reload();
  await page.getByRole('tab', { name: /^Stems/ }).click();
  await expect(page.getByRole('button', { name: 'Mute Melody', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Reset mix', exact: true }).click();
  await page.getByRole('button', { name: 'New project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Make yourself at home.' })).toBeVisible();
  await page.getByLabel('Your name', { exact: true }).fill('Jamie Lee');
  await page.getByLabel('Email address', { exact: true }).fill('jamie@example.test');
  await page.getByLabel('Password', { exact: true }).fill('studio-test-password');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.locator('#modal')).not.toBeVisible();
  const rate = 22050; const samples = Float32Array.from({ length: rate * 3 }, (_, i) => Math.sin(i / rate * Math.PI * 2 * 440) * .2);
  const wav = encodeWav({ numberOfChannels: 1, sampleRate: rate, length: samples.length, getChannelData: () => samples });
  await page.locator('#file-input').setInputFiles({ name: 'My first recording.wav', mimeType: 'audio/wav', buffer: Buffer.from(wav) });
  await expect(page.locator('.project-title h2')).toContainText('My first recording');
  await page.getByRole('tab', { name: 'Analysis', exact: true }).click();
  await expect(page.locator('.analysis-grid')).toContainText('Mono');
  await page.getByRole('tab', { name: 'Transcript', exact: true }).click();
  await page.locator('#transcript-text').fill('My handwritten transcript.');
  await page.getByRole('button', { name: 'Save text', exact: true }).click();
  await page.getByRole('button', { name: 'My projects', exact: false }).click();
  await page.getByRole('button', { name: 'My first recording', exact: true }).click();
  await page.getByRole('tab', { name: 'Transcript', exact: true }).click();
  await expect(page.locator('#transcript-text')).toHaveValue('My handwritten transcript.');
  await page.getByRole('button', { name: 'Auto-transcribe', exact: true }).click();
  await expect(page.locator('#modal')).toContainText('No AI service is connected');
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('button', { name: 'Export audio', exact: true }).click();
  await page.getByLabel('Start (seconds)', { exact: true }).fill('1');
  await page.getByLabel('End (seconds)', { exact: true }).fill('2');
  await page.getByLabel('Fade in (seconds)', { exact: true }).fill('0.1');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export & download', exact: true }).click();
  const download = await downloadPromise;
  const exported = await readFile(await download.path());
  expect(exported.toString('ascii', 0, 4)).toBe('RIFF');
  expect(exported.readUInt32LE(40)).toBe(44100 * 4);
  await page.getByRole('button', { name: 'Export center', exact: true }).click();
  await expect(page.locator('.export-row')).toHaveCount(1);
  await page.getByRole('button', { name: 'My projects', exact: false }).click();
  await page.getByLabel('Find a project').fill('first');
  await expect(page.locator('#search-results')).toContainText('My first recording');
  await page.locator('#search-results button').click();
  const register = await page.request.post('/api/register', { data: { name: 'New Artist', email: 'artist@example.test', password: 'another-test-password' } });
  expect(register.status()).toBe(201);
  await page.getByRole('button', { name: 'User approvals', exact: true }).click();
  await expect(page.locator('.admin-user').filter({ hasText: 'New Artist' })).toContainText('pending');
  await page.locator('.admin-user').filter({ hasText: 'New Artist' }).getByRole('button', { name: 'Approve', exact: true }).click();
  await expect(page.locator('.admin-user').filter({ hasText: 'New Artist' })).toContainText('active');
  await page.locator('.nav-item[data-page="workspace"]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Open navigation', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.locator('.toast')).toHaveCount(0, { timeout: 7000 });
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await expect(page.locator('#sidebar')).toHaveClass(/mobile-open/);
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'The little details.' })).toBeVisible();
  expect(errors).toEqual([]);
});
